import sqlite3
from flask import Flask, render_template_string, request

app = Flask(__name__)

def init_db():
    conn = sqlite3.connect('coffee_shop.db')
        cursor = conn.cursor()
            cursor.execute('''
                    CREATE TABLE IF NOT EXISTS menu (
                                id INTEGER PRIMARY KEY AUTOINCREMENT,
                                            name TEXT NOT NULL,
                                                        price REAL NOT NULL
                                                                )
                                                                    ''')
                                                                        cursor.execute('''
                                                                                CREATE TABLE IF NOT EXISTS sales (
                                                                                            id INTEGER PRIMARY KEY AUTOINCREMENT,
                                                                                                        table_num INTEGER,
                                                                                                                    item_name TEXT,
                                                                                                                                quantity INTEGER,
                                                                                                                                            total REAL
                                                                                                                                                    )
                                                                                                                                                        ''')
                                                                                                                                                            cursor.execute("SELECT COUNT(*) FROM menu")
                                                                                                                                                                if cursor.fetchone()[0] == 0:
                                                                                                                                                                        cursor.executemany("INSERT INTO menu (name, price) VALUES (?, ?)", [
                                                                                                                                                                                    ('Espresso', 1.50),
                                                                                                                                                                                                ('Iced Latte', 2.00),
                                                                                                                                                                                                            ('Americano', 1.75)
                                                                                                                                                                                                                    ])
                                                                                                                                                                                                                        conn.commit()
                                                                                                                                                                                                                            conn.close()

                                                                                                                                                                                                                            init_db()

                                                                                                                                                                                                                            @app.route('/')
                                                                                                                                                                                                                            def index():
                                                                                                                                                                                                                                table = request.args.get('table', 1)
                                                                                                                                                                                                                                    conn = sqlite3.connect('coffee_shop.db')
                                                                                                                                                                                                                                        cursor = conn.cursor()
                                                                                                                                                                                                                                            cursor.execute("SELECT * FROM menu")
                                                                                                                                                                                                                                                items = cursor.fetchall()
                                                                                                                                                                                                                                                    conn.close()
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                            html = '''
                                                                                                                                                                                                                                                                <!DOCTYPE html>
                                                                                                                                                                                                                                                                    <html>
                                                                                                                                                                                                                                                                        <head><title>Coffee Order</title><meta name="viewport" content="width=device-width, initial-scale=1"></head>
                                                                                                                                                                                                                                                                            <body style="font-family:sans-serif; padding:20px;">
                                                                                                                                                                                                                                                                                    <h2>☕ កុម្ម៉ង់កាហ្វេ (តុលេខ {{table}})</h2>
                                                                                                                                                                                                                                                                                            {% for item in items %}
                                                                                                                                                                                                                                                                                                        <div style="border:1px solid #ccc; padding:10px; margin-bottom:10px; border-radius:8px;">
                                                                                                                                                                                                                                                                                                                        <b>{{ item[1] }}</b> - ${{ "%.2f"|format(item[2]) }}
                                                                                                                                                                                                                                                                                                                                        <form action="/order" method="POST" style="margin-top:5px;">
                                                                                                                                                                                                                                                                                                                                                            <input type="hidden" name="table" value="{{table}}">
                                                                                                                                                                                                                                                                                                                                                                                <input type="hidden" name="item_name" value="{{ item[1] }}">
                                                                                                                                                                                                                                                                                                                                                                                                    <input type="hidden" name="price" value="{{ item[2] }}">
                                                                                                                                                                                                                                                                                                                                                                                                                        បរិមាណ: <input type="number" name="qty" value="1" min="1" style="width:50px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                            <button type="submit" style="background:green; color:white; border:none; padding:5px 10px; border-radius:4px;">កុម្ម៉ង់</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {% endfor %}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <br><a href="/admin">👨‍💼 ទៅកាន់ Admin Dashboard</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '''
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return render_template_string(html, items=items, table=table)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @app.route('/order', methods=['POST'])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def order():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            table = request.form.get('table')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                item_name = request.form.get('item_name')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    price = float(request.form.get('price'))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        qty = int(request.form.get('qty'))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            total = price * qty

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                conn = sqlite3.connect('coffee_shop.db')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cursor = conn.cursor()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cursor.execute("INSERT INTO sales (table_num, item_name, quantity, total) VALUES (?, ?, ?, ?)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           (table, item_name, qty, total))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               conn.commit()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   conn.close()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       return f"<h3>✅ បានកុម្ម៉ង់រៀបរយ! តុ {table}: {item_name} x{qty} (${total:.2f})</h3><a href='/?table={table}'>ត្រឡប់ក្រោយ</a>"

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       @app.route('/admin')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       def admin():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           conn = sqlite3.connect('coffee_shop.db')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               cursor = conn.cursor()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   cursor.execute("SELECT SUM(total) FROM sales")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       result = cursor.fetchone()[0]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           grand_total = result if result else 0.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               cursor.execute("SELECT * FROM sales ORDER BY id DESC LIMIT 20")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   sales = cursor.fetchall()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       conn.close()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           html = '''
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <!DOCTYPE html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <head><title>Admin Dashboard</title><meta name="viewport" content="width=device-width, initial-scale=1"></head>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <body style="font-family:sans-serif; padding:20px; background:#f4f4f4;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <h1>👨‍💼 ផ្ទាំងគ្រប់គ្រងម្ចាស់ហាង</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <div style="background:#2c3e50; color:white; padding:15px; border-radius:8px; text-align:center;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <h2>ចំណូលសរុប៖ ${{ "%.2f"|format(grand_total) }}</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <h3>📊 ប្រវត្តិលក់</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <table border="1" cellpadding="8" style="width:100%; border-collapse:collapse; background:white;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <tr><th>តុ</th><th>ទំនិញ</th><th>ចំនួន</th><th>សរុប</th></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       {% for s in sales %}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <tr><td>តុ {{s[1]}}</td><td>{{s[2]}}</td><td>{{s[3]}}</td><td>${{ "%.2f"|format(s[4]) }}</td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               {% endfor %}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <br><a href="/">⬅️ ត្រឡប់ទៅទំព័រអតិថិជន</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           '''
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               return render_template_string(html, grand_total=grand_total, sales=sales)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               if __name__ == '__main__':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   app.run(host='0.0.0.0', port=8000)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   